import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateSongs,poolFor,createGame,answerGame,nextQuestion,mistakes,wordForm,recordKey} from './game.mjs';
const songs=JSON.parse(fs.readFileSync(new URL('./songs.json',import.meta.url),'utf8'));
function seeded(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
test('В опубликованной подборке 241 уникальная песня и все 241 картинки доступны',()=>{assert.equal(validateSongs(songs).length,241);assert.equal(poolFor(songs,'guitar').length,85);assert.equal(poolFor(songs,'screenshots').length,26);assert.ok(poolFor(songs,'english').length>=4);for(const s of songs)assert.ok(fs.statSync(new URL(s.image,import.meta.url)).size>0);});
test('Партии не повторяют картинки; каждый вопрос имеет четыре разных ответа и ровно один правильный',()=>{for(const pack of ['all','guitar','screenshots','english'])for(let seed=1;seed<=50;seed++){const game=createGame(songs,pack,30,seeded(seed));assert.equal(new Set(game.questions.map(q=>q.song.id)).size,game.questions.length);assert.equal(game.questions.length,Math.min(30,poolFor(songs,pack).length));for(const q of game.questions){assert.equal(q.options.length,4);assert.equal(new Set(q.options.map(s=>s.id)).size,4);assert.equal(q.options.filter(s=>s.id===q.song.id).length,1);assert.ok(q.options.every(s=>pack==='all'||s.categories.includes(pack)));}}});
test('Повторное нажатие не начисляет очки; неверный ответ и пропуск сбрасывают серию',()=>{const game=createGame(songs,'all',4,seeded(6));assert.equal(nextQuestion(game),false);let q=game.questions[0];assert.equal(answerGame(game,q.song.id).points,100);assert.equal(answerGame(game,q.song.id),null);assert.equal(game.score,100);nextQuestion(game);q=game.questions[1];answerGame(game,q.song.id);assert.equal(game.streak,2);nextQuestion(game);q=game.questions[2];answerGame(game,q.options.find(s=>s.id!==q.song.id).id);assert.equal(game.score,200);assert.equal(game.streak,0);nextQuestion(game);answerGame(game,null);assert.equal(game.score,200);assert.equal(mistakes(game).length,2);assert.equal(nextQuestion(game),false);assert.equal(game.finished,true);assert.equal(answerGame(game,q.song.id),null);assert.equal(game.bestStreak,2);});
test('Полностью правильная партия даёт 2000 очков и не содержит ошибок',()=>{const game=createGame(songs,'guitar',20,seeded(18));while(!game.finished){answerGame(game,game.questions[game.index].song.id);nextQuestion(game);}assert.equal(game.score,2000);assert.equal(game.correctCount,20);assert.equal(mistakes(game).length,0);});
test('Рекорды разных подборок и длины партии независимы',()=>{assert.notEqual(recordKey(createGame(songs,'all',10)),recordKey(createGame(songs,'all',20)));assert.notEqual(recordKey(createGame(songs,'guitar',20)),recordKey(createGame(songs,'all',20)));assert.equal(createGame(songs,'screenshots',30).questions.length,26);});
test('Неверные данные и ответы отвергаются',()=>{assert.throws(()=>validateSongs([...songs,songs[0]]));assert.throws(()=>createGame(songs,'unknown'));assert.throws(()=>createGame(songs,'all',0));const game=createGame(songs,'all',10);assert.throws(()=>answerGame(game,'not-a-song'));assert.equal(game.score,0);});
test('Русские числительные корректны для 1, 2, 5, 11, 21, 85 и 241',()=>{assert.deepEqual([1,2,5,11,21,85,241].map(n=>wordForm(n,'песня','песни','песен')),['песня','песни','песен','песен','песня','песен','песня']);});
