import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRoom,joinRoom,startRoom,readyRoom,answerRoom,tickRoom,advanceRoom,snapshot,roundKey,disconnectPlayer,pointsFor,MAX_PLAYERS} from './room.mjs';
const songs=JSON.parse(readFileSync(new URL('./songs.json',import.meta.url)));
const profile=n=>({id:`player-${String(n).padStart(20,'0')}`,token:`secret-${String(n).padStart(20,'0')}`,name:`Игрок ${n}`});
function setup(rounds=4){const r=createRoom(songs,'all',rounds,'nonce',()=>.3);joinRoom(r,profile(1));joinRoom(r,profile(2));startRoom(r);return r;}
function ready(r,now=1000){readyRoom(r,null,roundKey(r),now);readyRoom(r,profile(1).id,roundKey(r),now);readyRoom(r,profile(2).id,roundKey(r),now);tickRoom(r,now+3000);}
test('100 minus full elapsed seconds, including exact boundaries',()=>{for(const [ms,points] of [[0,100],[4999,96],[5000,95],[99999,1],[100000,0]])assert.equal(pointsFor(ms),points);});
test('all images ready before shared countdown',()=>{const r=setup();readyRoom(r,null,roundKey(r),1000);readyRoom(r,profile(1).id,roundKey(r),2000);assert.equal(r.phase,'prepare');readyRoom(r,profile(2).id,roundKey(r),9000);assert.equal(r.startAt,12000);tickRoom(r,11999);assert.equal(r.phase,'countdown');tickRoom(r,12000);assert.equal(r.phase,'question');});
test('host time, no early reveal, no duplicate/stale/foreign answer',()=>{const r=setup();ready(r);const id=profile(1).id,key=roundKey(r),right=r.questions[0].song.id;assert.equal(answerRoom(r,id,key,'invented',9000),false);assert.equal(answerRoom(r,id,'old',right,9000),false);assert.equal(answerRoom(r,id,key,right,9000),true);assert.equal(answerRoom(r,id,key,null,9001),false);const waiting=snapshot(r,profile(2).id,9001);assert.equal(waiting.question.song,undefined);assert.equal(waiting.result,null);assert.equal(waiting.players[0].score,0);answerRoom(r,profile(2).id,key,null,9500);tickRoom(r,9500);assert.equal(r.phase,'reveal');assert.equal(snapshot(r,id,9500).result.points,95);assert.equal(snapshot(r,profile(2).id,9500).result.points,0);});
test('wrong/timeout zero; late answer rejected',()=>{const r=setup();ready(r);const wrong=r.questions[0].options.find(s=>s.id!==r.questions[0].song.id).id;answerRoom(r,profile(1).id,roundKey(r),wrong,4010);tickRoom(r,104000);assert.equal(r.phase,'reveal');assert.equal(r.players[0].score,0);assert.equal(r.players[1].score,0);assert.equal(answerRoom(r,profile(2).id,roundKey(r),r.questions[0].song.id,104001),false);});
test('disconnect does not block loading; reconnect retains score and requires token',()=>{const r=setup();readyRoom(r,null,roundKey(r),1000);readyRoom(r,profile(1).id,roundKey(r),1000);disconnectPlayer(r,profile(2).id,2000);assert.equal(r.phase,'countdown');tickRoom(r,5000);answerRoom(r,profile(1).id,roundKey(r),r.questions[0].song.id,10000);tickRoom(r,10000);assert.equal(r.players[0].score,95);disconnectPlayer(r,profile(1).id,11000);assert.ok(joinRoom(r,{...profile(1),token:'other-secret-00000000000000'}).error);assert.ok(joinRoom(r,profile(1)).player);assert.equal(r.players[0].score,95);assert.ok(joinRoom(r,profile(3)).error);});
test('ranking every 3 songs and final cumulative ranking',()=>{const r=setup(7);for(let i=0;i<7;i++){const now=1000+i*20000;ready(r,now);const key=roundKey(r),right=r.questions[i].song.id;answerRoom(r,profile(1).id,key,right,now+8000);answerRoom(r,profile(2).id,key,right,now+13000);tickRoom(r,now+13000);assert.equal(r.phase,'reveal');advanceRoom(r);if(i===6)assert.equal(r.phase,'finished');else if((i+1)%3===0){assert.equal(r.phase,'leaderboard');advanceRoom(r);}else assert.equal(r.phase,'prepare');}const s=snapshot(r,null,200000);assert.equal(s.players[0].name,'Игрок 1');assert.equal(s.players[0].score,7*95);assert.equal(s.players[1].score,7*90);assert.equal(s.players[1].rank,2);});
test('50 participants may join, but the 51st cannot; credentials/messages remain bounded',()=>{assert.equal(MAX_PLAYERS,50);const r=createRoom(songs,'guitar',10,'nonce');assert.ok(joinRoom(r,null).error);assert.ok(joinRoom(r,{...profile(1),name:'name\u0001'}).error);for(let n=1;n<=MAX_PLAYERS;n++)assert.ok(joinRoom(r,profile(n)).player);assert.ok(joinRoom(r,profile(MAX_PLAYERS+1)).error);assert.equal(startRoom(r),true);assert.equal(startRoom(r),false);assert.equal(advanceRoom(r),false);});
test('all 50 participants share one start, answer once and appear in the final ranking',()=>{const r=createRoom(songs,'all',1,'large-party',()=>.3);for(let n=1;n<=50;n++)joinRoom(r,profile(n));startRoom(r);const key=roundKey(r);readyRoom(r,null,key,1000);for(let n=1;n<=49;n++)readyRoom(r,profile(n).id,key,1000);assert.equal(r.phase,'prepare');readyRoom(r,profile(50).id,key,1000);assert.equal(r.phase,'countdown');tickRoom(r,4000);for(let n=1;n<=50;n++){assert.equal(answerRoom(r,profile(n).id,key,r.questions[0].song.id,4000+n*100),true);assert.equal(answerRoom(r,profile(n).id,key,null,4000+n*100),false);}tickRoom(r,9000);assert.equal(r.phase,'reveal');advanceRoom(r);const state=snapshot(r,null,9000);assert.equal(state.phase,'finished');assert.equal(state.players.length,50);assert.equal(state.players[0].score,100);assert.equal(state.players[49].score,95);});
